### ISSUE TITLE
Change absolute hrefs to relative

### ISSUE THREAD

**Issue by Kamori** [joevegan/ticketdesk#10]
These lines will cause some breakage for new installs due to a hard hostname provided, or a subdirectory defined. 

Examples

https://github.com/joevegan/ticketdesk/blob/cb38ac58661e7e2ed6fcf23d9d94ae964c32f123/include/process_reset.php#L19-L48
https://github.com/joevegan/ticketdesk/blob/7a395015eeba7d112a16751f741155646a63ceb7/include/navbar.php#L35
https://github.com/joevegan/ticketdesk/blob/7a395015eeba7d112a16751f741155646a63ceb7/include/navbar.php#L54
https://github.com/joevegan/ticketdesk/blob/40b02dded1447275ea818c7d02276acdb2ef6e32/tickets.php#L47

**Comment by Kamori** [comment]
links in include/navbar.php would be fixed by the following pr

https://github.com/joevegan/ticketdesk/pull/11

**Comment by joevegan** [comment]
awesome, I merged in the pr. I'll push up to the demo server tonight! thanks again for committing!
