### ISSUE TITLE
What is the default email id and password

### ISSUE THREAD

**Issue by UmairVarin** [joevegan/ticketdesk#24]

**Comment by joevegan** [comment]
There is no default user created, you can use the register page to make your first user

**Comment by UmairVarin** [comment]
but there is nothing happening, stucked.

**Comment by UmairVarin** [comment]
but there is nothing happening, stucked.

**Comment by joevegan** [comment]
You ran the install script? Can you get to the register.php page?

**Comment by UmairVarin** [comment]
Hi,

Send this test email to get an open notification when the recipient reads
it.

Thanks.

PS: Please ensure that you do not open the email from the registered email
address with SalesHandy to test, as our system excludes self-open
notification.
